mumprod/hr-design-system-handlebars

.github/workflows/release.yml, package.json
to make sure dist folder is in package
=> calls clean script before build script

.github/workflows/release.yml
https://github.com/intuit/auto/issues/1030
=> add unset header step according to

src/stories/views/components/Label.hbs, src/stories/views/components/Label.stories.mdx, tailwind.config.js
- addjusted letter spacing in tailwind.config.js
=> - New Story for Label Component

src/assets/css/tailwind.css
to make sure that the selectors aren't purged
by purgecss
=> adds comment in front of theme selectors

src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutColumn.hbs, src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutItem.hbs, src/stories/views/components/Header/serviceNavigationData.json
- items in colums are in a array now
- fixed columns template so it is compatible with delivery
=> fixed columns template so it is compatible with delivery now

src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs, src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutColumn.hbs, src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutItem.hbs, src/stories/views/components/Header/serviceNavigationData.json, src/stories/views/components/base/link.hbs
- added block template link.hbs to project
- implemented link.hbs to NavigationFlyoutItem.hbs
- refactored navigationFlyout.hbs
- extended serviceNavigation.json with link functionality for menu items
=> Added block template link.hbs to project

.storybook/withThemeDecorator.js, src/stories/views/components/Header/BrandNavigation/BrandNavigation.hbs, src/stories/views/components/Header/BrandNavigation/BrandNavigationItem.hbs, src/stories/views/components/Header/BrandNavigation/BrandNavigationItem.stories.mdx, src/stories/views/components/Header/Header.hbs, src/stories/views/components/Header/Header.stories.mdx, src/stories/views/components/Header/SectionNavigation/SectionNavigation.hbs, src/stories/views/components/Header/SectionNavigation/SectionNavigation.stories.mdx, src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.hbs, src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.stories.mdx, src/stories/views/components/Header/ServiceNavigation/ServiceNavigation.hbs, src/stories/views/components/Header/ServiceNavigation/ServiceNavigation.stories.mdx, src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs, src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.stories.mdx, src/stories/views/components/Header/navigation.json
=> Some tailwind stuff for the navi

build/helpers/isStorybook.js, src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.stories.mdx, src/stories/views/components/Header/ServiceNavigation/ServiceList.hbs, src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs, src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.stories.mdx, src/stories/views/components/Header/navigation.json, src/stories/views/components/Header/serviceNavigationData.json, src/stories/views/components/base/loadSSI.hbs
- added isStorybook helper
- added loadSSI.hbs (not working yet)
- changed data structure of navigation JSONs
-  changed templates for delivery support
=> Storybook Modul > SSI Helper

.github/workflows/release.yml
bahmutov/npm-install@v1.6.0 action
=> replaces reading npm cache with

.storybook/main.js, package.json, src/stories/views/components/Header/BrandNavigation/BrandNavigation.stories.mdx, src/stories/views/components/Header/BrandNavigation/BrandNavigationItem.stories.mdx, src/stories/views/components/Header/Header.stories.mdx, src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.stories.mdx, src/stories/views/components/Header/Search/QuickSearchButton.stories.mdx, src/stories/views/components/Header/Search/QuickSearchForm.stories.mdx, src/stories/views/components/Header/SectionNavigation/SectionNavigation.stories.mdx, src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.stories.mdx, src/stories/views/components/Header/ServiceNavigation/ServiceList.stories.mdx, src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.stories.mdx, src/stories/views/components/Label.stories.mdx, src/stories/views/components/Page/Page.stories.mdx
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
=> updates deprecated features according to

src/stories/views/components/Header/Header.hbs, src/stories/views/components/Header/navigation.json, src/stories/views/components/Header/navigation2.json, src/stories/views/components/Header/navigation3.json, src/stories/views/components/Page/Page.hbs, tailwind.config.js
-moved <header> Tag to header.hbs
- hight in Desktop view depends on hasOpenSubNavigation
- navigation jsons have information hasOpenSubNavigation
- added some heights to tailwind.config
=> Dynamic hight for <header> tag depending on hasOpenSubNavigation

src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs, src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutColumn.hbs
- changed layout for section Navigation
- margin left was wrong on edge from md to lg
=> Navi:Bug: Abstand des ersten Eintrages in der SubNav in Desktop

src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.hbs
- removed lg:last:pr-8 class from last service icon
=> DPE-1388: Abstand letztes Sevice Icon zu groß

src/assets/tailwind.css, src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs, src/stories/views/components/Header/NavigationFlyout/NavigationFlyoutColumn.hbs, src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.hbs
- refactoring to remove width bug
=> DPE-1391 Navi: Bug: Regionen Flyout(Cluster) fehlerhaft wenn Eintrag länger

src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.stories.mdx, src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.hbs, src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.stories.mdx, src/stories/views/components/Header/ServiceNavigation/ServiceNavigationItem.stories.mdx, src/stories/views/components/Header/navigation.json, src/stories/views/components/Header/navigation2.json, src/stories/views/components/Header/navigation3.json, src/stories/views/components/Header/serviceNavigationData.json
navigation json structure was wrong so @first could not be used correctly in handlebars template
=> navigation json structure was wrong

src/stories/views/components/Header/Burger.hbs, src/stories/views/components/Header/Header.hbs, src/stories/views/components/Header/Search/QuickSearchButton.hbs, src/stories/views/components/Header/ServiceNavigation/ServiceList.hbs
- refactoring of allowScrolling. new name toggleScrolling
- Overlay has ontouchmove preventDefault now
=> DPE-1407 iOS mobile/tablet: auf Endgerät ist body noch scrollbar

src/assets/tailwind.css, src/stories/views/components/Header/NavigationFlyout/NavigationFlyout.hbs, src/stories/views/components/Header/SectionNavigation/SectionNavigationItem.hbs, src/stories/views/components/Header/navigation2.json
- added extra condition to distinguish selected from showAsFlyout style
- moved :before arrow element into button/a so positioning is easier
=> DPE-1477 - Regionen Flyout falsch wenn man auf einer Regionenseite ist

src/assets/tailwind.css
position absolute only in Desktop View for -current election pseudo element
=> DPE-1491 - Pfeil vom Burger erscheint auch ohne Burger

src/stories/views/components/Page/Page.stories.mdx
snapshots for viewports at 360, 768 and
1024 pixels
=> FEATURE: configures chromatic to make

.storybook/main.js
the tailwind.css when a compilation is f
inished and hence the tailwind jit compiler is run
=> FEATURE: adds webpackplugin that always saves

.storybook/preview.js, src/stories/views/components/Teaser/Teaser-Heading.hbs, src/stories/views/components/Teaser/Teaser-standard.hbs, src/stories/views/components/Teaser/Topline.hbs, src/stories/views/components/Teaser/data/16_7_teaserImage.json, src/stories/views/components/Teaser/data/16_9_teaserImage.json, src/stories/views/components/Teaser/data/teaser_standard_lg_serif.json, src/stories/views/components/Teaser/data/teaser_standard_md_serif.json, src/stories/views/components/Teaser/data/teaser_standard_sm_serif.json, src/stories/views/components/Teaser/data/teaser_standard_xl_serif.json, src/stories/views/components/Teaser/data/teaser_standard_xxl_serif.json, src/stories/views/components/Teaser/teaser-standard.stories.mdx, src/stories/views/components/base/image/responsiveImage.hbs
- added loadDelayedImages() functionality
- extracted teaserImage.json
=> responsiveImage 2.0

src/assets/tailwind.css, src/stories/views/components/Teaser/Teaser-standard.hbs
- teaser get new aspect ratio classes depending on size
=> - added aspect ratio classes with fallback to tailwind.css

src/stories/views/components/base/image/responsive_image.hbs, src/stories/views/components/teaser/teaser_alternativ.hbs, src/stories/views/components/teaser/teaser_standard.hbs
- removed parameter classes from teaser_alternative and teaser_standard
=> - removed css classes from responsive_image.hbs

build/scripts/build.js
the feature-loader are copied into
the dist folder, when the project
ist build.
=> FEATURE: All js files that get loaded by

src/stories/views/components/button/button_pseudo.hbs, src/stories/views/components/teaser/components/teaser_heading.hbs
when calling button_pseudo.inc.hbs
=> BUGFIX: Explicitely sets partial properties

.storybook/preview-head.html, package-lock.json, package.json
- changed script tag to new version in preview-head.html
=> Installed async-alpine as npm module v.1.0.0

src/stories/views/components/mediaplayer/media_player.hbs, src/stories/views/components/teaser/components/teaser_image.hbs
- changed _noDelay=../this.dontLazyload to _noDelay=this.dontLazyload
- context wasn't working in storybook
- changed _noDelay=../_noDelay to _noDelay=this.dontLazyload. wasn't working
=> DPE-1978 SEO - lazyloading bei ersten Teaser funktioniert bei AV Teasern nicht

src/stories/views/components/teaser/cluster/teaser_cluster_item.hbs, src/stories/views/components/teaser/cluster/teaser_cluster_list.hbs, src/stories/views/components/teaser/components/teaser_body.hbs, src/stories/views/components/teaser/teaser_poster.hbs
changed teaserSize to realTeaserSize in teaser_heading.hbs calls
=>  realTeaserSize for DPE-1982

src/stories/views/components/teaser/group_teaser/group_teaser_accented.hbs
- removed margin from accented group
- refactored wrapper div
=> DPE-2002 - Fehler bei Akzentuiergruppen

src/stories/views/components/mediaplayer/media_player.hbs, src/stories/views/components/teaser/components/teaser_body.hbs, src/stories/views/components/teaser/components/teaser_image.hbs, src/stories/views/components/teaser/teaser_alternativ.hbs, src/stories/views/components/teaser/teaser_standard.hbs
Unneccessary div is removed from teaser_image component. Teaser Body is displayed
in full width, when a media element is played
in mobile viewports.
=> FEATURE: Removes unneccessary div in teaser_image and fixes css problems

src/stories/views/components/teaser/cluster/teaser_cluster.hbs, src/stories/views/components/teaser/components/teaser_body.hbs, src/stories/views/components/teaser/teaser_alternativ.hbs, src/stories/views/components/teaser/teaser_poster.hbs, src/stories/views/components/teaser/teaser_standard.hbs
- margin x for teasers are set to 0px allready on sm breakpoint
=> Seitenabstände in "Tablet"-Ansicht anpassen

src/assets/css/custom-components.css, src/stories/views/components/teaser/cluster/teaser_cluster_item.hbs, src/stories/views/components/teaser/cluster/teaser_cluster_list.hbs
first teaser with teaserImage ihas linked image now
=> Bild in Cluster-Teaser nicht verlinkt

.github/workflows/chromatic.yml
only on push in main and active prs
=> REFAC: Updates chromatic build script to run

src/stories/views/components/teaser/teaser_standard.hbs
event teaser in viewports up to 768 px
=> BUGFIX: Fixes the layout of standard 100%

src/stories/views/components/teaser/podcast/podcast_item_title.hbs
https://jira.ard.de/browse/DPE-2128
=> DPE-2128 Überschriften Hover bei Podcast Channel Player

src/stories/views/components/teaser/components/teaser_body.hbs
added md:pr-0 so titel of 25% Teaser dont breaks in desktop view
=> Titel bricht um, wenn man Video startet bei 25% Teasern

src/stories/views/components/teaser/components/teaser_text.hbs
https://jira.ard.de/browse/DPE-2141
=> DPE-2141 Teaser: Link-Icon hängt in neuer Zeile

.storybook/preview.js, README.md, src/stories/InstallAndUpdate.stories.mdx
upgrade process of Node Packages withh yarn
=> DOC: Adds documentation for the installation and

src/stories/views/components/button/top_topics_button.hbs, src/stories/views/components/tracking/download_tracking.hbs, src/stories/views/components/tracking/navigation_tracking.hbs
=> DPE-2294 Topthemen: Tracking

src/stories/views/base/tracking/atiHelper.subfeature.js
helper to make sure that the old tracking works
=> BUGFIX: Revert changes to tracking

src/assets/vendor/js/podcast_player.alpine.js
=> BUGFIX: Changes property names so that data

src/assets/tailwind.css, src/stories/views/base/tracking/clickTracking.feature.js, src/stories/views/components/teaser/components/teaser_text.hbs, src/stories/views/components/tracking/navigation_tracking.hbs
fixed soe bugs:
https://jira.ard.de/browse/DPE-2419 JS-Fehler in der Konsole
https://jira.ard.de/browse/DPE-2415 hr-info navi farbe
=> Bugfix release 2023 07 19

src/assets/vendor/js/podcast_player.alpine.new.js
- removed new podcast piano tracking
- new file with piano tracking
=> DPE-2419  - JS-Fehler in der Konsole

src/stories/views/components/footer/page_footer.hbs, src/stories/views/components/site_header/navigation_search/quick_search_form.hbs
=> FEATURE: label footer and quicksearch-form

src/stories/views/components/content_nav/content_nav_item.hbs
- adjusted icon size and margin-left
- removed whitespace
=> DPE-2205 - Contentnavi Button mit zusätzlichen Icon versehen

src/stories/views/components/podcast/components/podcast_subscribe_button.hbs
changed z-index of subscribe button to 50 so it is overlayed by menu layover(z-index 100)
=> DPE-2550 - Button hängt über Hintergrund-

src/stories/views/components/modal/modal.hbs
quotes around trackingInformations
=> :bug: DPE-2646 - Remove

src/stories/views/components/banner/banner.storybook.hbs, src/stories/views/components/page/page.hbs, src/stories/views/components/top_button/top_button.hbs
- fixed bug with scroll to to on click everywhere
- removed scroll to top from banner story
- added footer an scroll to top to page story
=> DPE-2673-1

src/stories/views/components/article/components/podcast/podcast_episode-webview.hbs, src/stories/views/components/article/components/podcast/podcast_playlist-webview.hbs
- changed path to template in playlist webview
- episode webview added _webview=true param
=> Podcast webview Bug

src/stories/views/components/footer/page_footer_social_media.hbs
https://jira.ard.de/browse/DPE-2705
=> DPE-2705 Social Links im Footer bekommen falsche Fokus Klassen

build/scripts/build.js
https://jira.ard.de/browse/DPE-2056
=> DPE-2056 Teaser: Locatags aus Designsystem mit Locatags aus Delivery mergen

src/assets/css/custom-utilities.css, src/stories/views/components/banner/header/banner_image.hbs, src/stories/views/components/banner/header/banner_overlay.hbs, src/stories/views/components/banner/header/banner_wrapper.hbs, src/stories/views/components/banner/header/breadcrumb_wrapper.hbs, src/stories/views/components/banner/structure_nav/structure_nav.hbs
Banner image should be hidden in print view
=> Banner print view bug

src/stories/views/components/banner/header/banner_wrapper.hbs
add ar-auto for banner wrapper
=> Banner print bug 2

src/stories/views/components/site_header/anchor_navigation/anchor_navigation.hbs, src/stories/views/components/site_header/anchor_navigation/featurebox_anchor.hbs, src/stories/views/components/site_header/header.hbs
=> :bug: make anchor nav visible for screenreaders

src/assets/tailwind.css, src/stories/views/components/site_header/navigation_search/quick_search_form.hbs, tailwind.config.js
https://jira.ard.de/browse/DPE-2706
=> Dpe-2706 Lupe in Suchfeld hat falsche Farbe

src/stories/views/base/tracking/clickTracking.feature.js, src/stories/views/base/tracking/pianoHelper.subfeature.js
=> :sparkles: Make pi method parameterless

src/assets/css/custom-utilities.css, src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs, src/stories/views/components/site_header/service_logo.hbs, src/stories/views/components/site_header/service_navigation/service_navigation_item.hbs
-use a focus color that suits for ALL sites
=> -change "link-focus-inset-white" to "link-focus-inset"

.storybook/preview.js, src/stories/views/components/horizontal_scroll_container/horizontal_scroll_container.alpine.js, src/stories/views/components/horizontal_scroll_container/horizontal_scroll_container.hbs, src/stories/views/components/horizontal_scroll_container/horizontal_scroll_container_example.hbs
- changed resize hadler to resizeObserver
=> Scrollpfeil bei hauptnavi sichtbar obwohl nicht nötig

src/stories/views/components/site_header/navigation_flyout/navigation_flyout_item.hbs, src/stories/views/components/site_header/section_navigation/section_navigation_item.hbs
- adds link-focus-inset in navigation_flyout_item
=> - fixes wrong tabindex  in section_navigation_item.hbs

src/stories/views/base/tracking/pianoHelper.subfeature.js
pageDisplayConfig object.
No TypeError is thrown when the pageDisplayConfig object doesn't exist
=> :bug: Fix the check for the existence of the

src/stories/views/components/mediaplayer/ardPlayerLoader.subfeature.js
AGF and Piano tracking work again.
=> :bug: use globalSettingsCookie instead of incompatible trackingCookie.

src/stories/views/components/site_header/navigation_flyout/navigation_flyout.hbs, src/stories/views/components/site_header/navigation_flyout/navigation_flyout_item.hbs
- SubNavigation has also grid layout now
- padding of Items is pl-5 in mobile now
=> 🐛 fix Bug in SubNavigation

.github/workflows/chromatic.yml, src/assets/css/custom-components.css, src/assets/tailwind.css, src/stories/views/components/site_header/service_navigation/service_navigation_item.hbs, tailwind.config.js
https://jira.ard.de/browse/DPE-2669
=> DPE-2669 Dark mode for Content-Navi 

src/stories/views/components/page/base/page_header.hbs
- moved label out of the h2 in Articles for SEO reasons
=> ✨ h-Auszeichnungen der Label überarbeiten

src/stories/views/components/page/components/metadatabox.hbs, src/stories/views/components/page/story/story_article.hbs
- add hideMetadatabox to prevent showing empty metadatabox
- added -adjust_context because of Context problems in Delivery
=> ✨ Webview Adjustments DPE-2945

src/stories/views/components/content/content_footer/content_footer.hbs
removed by accident, readded on purpose
=> readds hover css

src/stories/views/components/top_button/top_button.hbs
- top Button Wrapper has fix height. h-8
- isVisible is also true if footer is visible
=> Kein Abstand zum Footer - DPE-3207

src/assets/css/custom-components.css, src/stories/views/components/content/copytext/copytext.hbs, src/stories/views/components/content/copytext/copytext_body.hbs, src/stories/views/components/program_reference/program_reference.hbs
DPE-3210 - Darkmode: "Thema in" fehlt
DPE-3211 - Darkmode: Content-Navi im Artikel
DPE-3215 - Keine JSON-Metadaten für Bilder vorhanden
=> DPE-3210 AND DPE-3211- Darkmode bugs new story page

src/stories/views/components/content/copytext/components/common/paragraphbox_wrapper.hbs, src/stories/views/components/content/copytext/components/contentbox/contentbox.hbs, src/stories/views/components/content/copytext/components/contentbox/storybook-contentbox.hbs, src/stories/views/components/content/copytext/components/filedownload.hbs, src/stories/views/components/content/copytext/components/infobox.hbs
- removed overflow-auto and neg. margins from downloadbox infobox and contentbox.
=> DPE-3227 - Infobox: Umlaut-Großbuchstaben haben keine Punkte

src/stories/views/components/base/link.hbs
- added data-primary-type and data-json-url to link component
=> DPE-3232-  Data-Attribute fehlen bei Bildergalerie-Link

src/stories/views/components/social_sharing/socialSharingHandler.alpine.js, src/stories/views/components/social_sharing/social_sharing_copytext.hbs, src/stories/views/components/social_sharing/social_sharing_horizontal.hbs, src/stories/views/components/social_sharing/social_sharing_mobile.hbs
added additional uxAction, when sharing Button(mobile) is first time shown
=> Social Sharing Tracking- first time show added

src/stories/views/components/page/base/page_wrapper.hbs, src/stories/views/components/page/story/story_article.hbs, src/stories/views/components/page/story/story_main.stories.js
- margin in mbile view on page wrapper if is webview
=> DPE-3264 - Webview: Abstand von Dachzeile nach oben

src/stories/views/components/content/copytext/components/image/image.hbs
when viewed in mobile viewports
=> :lipstick: Display 50% images in portrait view in full width

src/stories/views/components/event/calendar/event_calendar_nav.hbs, src/stories/views/components/event/filtererDs.feature.js
https://jira.ard.de/browse/DPE-3121
=> :lipstick: Modify font color post UX review

src/stories/views/components/base/link.hbs
Adds click tracking for external links
=> :sparkles: add tracking for external links

src/stories/views/components/social_sharing/socialSharingHandler.alpine.js
https://jira.ard.de/browse/DPE-3358
=> DPE-3358 Falsche Vorschau beim Sharing von Dokumenten

src/stories/views/components/forms/components/backgroundBox.hbs, src/stories/views/components/forms/webform.hbs
=> - adds margin top to bgBox

src/stories/views/components/site_header/mainNavigationHandler.alpine.js, tailwind.config.js
- added scrollDown condition in Nav handler
=> - added classes to the safelist

src/assets/css/custom-components.css
=> fixes typo

src/stories/views/components/forms/components/choice.hbs, src/stories/views/components/forms/components/choiceGroup.hbs, src/stories/views/components/forms/components/input.hbs, src/stories/views/components/forms/components/select.hbs, src/stories/views/components/forms/components/upload.hbs
Update form components to use adjusted context for descriptions and required fields
=> Form Bug - Context Problems fixed

package.json, src/stories/views/components/mediaplayer/mediaPlayer_stickyWrapper.hbs, tailwind.config.js, yarn.lock
- Add tailwindcss-animated package and enhance media player sticky wrapper with animations
- added Close Button
=> DPE-1087 - Ticker: Livestreams ohne Unterbrechung (Enhancements)

src/stories/views/components/mediaplayer/mediaPlayer_stickyWrapper.hbs
Enhance media player sticky wrapper positioning based on subnavigation visibility
=> Enhance media player sticky wrapper positioning based on subnavigation visibility

src/stories/views/components/content/copytext/components/externalservice.hbs, src/stories/views/components/content/copytext/copytext_body.hbs, src/stories/views/components/external-service/dataWrapperNoResponsiveIframe.subfeature.js, src/stories/views/components/external-service/externalServiceDs.feature.js, src/stories/views/components/external-service/external_service.hbs, src/stories/views/components/external-service/external_service_with_datapolicy_check.hbs, src/stories/views/components/teaser/teaser_external_service.hbs
=> change _isFirst to _loadLazy & set _LoadLazy in Teaser to false
